<?php $_moduleHelper = $this->helper('Iods\Core\Helper\Module'); ?>

<style>
    table, th, td {
        padding: 5px 0.5em;
    }
</style>

<h2>System Information</h2>
<h3>Module</h3>
<table>
    <tbody>
    <tr>
        <td>Extension developer:</td>
        <td><a href="https://github.com/iods" title="Link to Github profile">Rye Miller</a><br><a href="#" title="Buy me a coffe">Buy me a coffee</a></td>
    </tr>
    <tr>
        <td>Module version:</td>
        <td><?php /* @noEscape */ echo $_moduleHelper->getModuleVersion(); ?></td>
    </tr>
    </tbody>
</table>
<h3>Magento</h3>
<table>
    <tbody>
    <tr>
        <td>Magento edition:</td>
        <td><?php /* @noEscape */ echo ucfirst($_moduleHelper->getMagentoEdition()); ?></td>
    </tr>
    <tr>
        <td>Magento version:</td>
        <td><?php /* @noEscape */ echo $_moduleHelper->getMagentoVersion(); ?></td>
    </tr>
    <tr>
        <td>Magento mode:</td>
        <td><?php /* @noEscape */ echo ucfirst($_moduleHelper->getMagentoMode()); ?></td>
    </tr>
    <tr>
        <td>Magento path:</td>
        <td><?php /* @noEscape */ echo $_moduleHelper->getMagentoPath(); ?></td>
    </tr>
    </tbody>
</table>
<h3>PHP</h3>
<table>
    <tbody>
    <tr>
        <td>PHP version:</td>
        <td><?php /* @noEscape */ echo phpversion(); ?></td>
        <td></td>
    </tr>
    <tr>
        <td>Memory limit:</td>
        <td><?php /* @noEscape */ echo ini_get('memory_limit'); ?></td>
        <td>max amount of memory a script may consume. This value should be at least as big as post_max_size</td>
    </tr>
    <tr>
        <td>Max execution time:</td>
        <td><?php /* @noEscape */ echo ini_get('max_execution_time'); ?></td>
        <td>max execution time of each script, in seconds</td>
    </tr>
    <tr>
        <td>Max input time:</td>
        <td><?php /* @noEscape */ echo ini_get('max_input_time'); ?></td>
        <td>max amount of time each script may spend parsing request data</td>
    </tr>
    <tr>
        <td>Max file uploads:</td>
        <td><?php /* @noEscape */ echo ini_get('max_file_uploads'); ?></td>
        <td>sets the maximum number of files that can be uploaded at a time</td>
    </tr>
    <tr>
        <td>Max file size:</td>
        <td><?php /* @noEscape */ echo ini_get('upload_max_filesize'); ?></td>
        <td>controls the maximum size of each file</td>
    </tr>
    <tr>
        <td>Max POST size:</td>
        <td><?php /* @noEscape */ echo ini_get('post_max_size'); ?></td>
        <td>max size of POST data that PHP will accept. This value should be at least as big as upload_max_filesize * max_file_uploads</td>
    </tr>
    <tr>
        <td>Max session lifetime:</td>
        <td><?php /* @noEscape */ echo ini_get('session.gc_maxlifetime'); ?></td>
        <td>specifies the number of seconds after which data will be seen as 'garbage' and potentially cleaned up. Be aware that the session lifetime value should be greater than Magento admin session lifetime unless you use Redis for session cache.</td>
    </tr>
    </tbody>
</table>